# Generated by Django 3.2.8 on 2021-10-25 13:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211024_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='post',
            field=models.ManyToManyField(to='posts.Post'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
