version: '3.8'

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/usr/src/forum
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - "./static/:/static"


